name: Practice for github actions
on: workflow_dispatch
jobs:
  generate-message:
    runs-on: ubuntu-latest
    outputs:
      daily-message: ${{ steps.set-msg.outputs.daily-message }}
    steps:
      - id: set-msg
        run: echo "daily-message=Hello from the scheduler!" >> $GITHUB_OUTPUT

  print-message:
    needs: generate-message
    runs-on: ubuntu-latest
    steps:
      - name: Display output from previous job
        run: |
          echo "The message is: '${{ needs.generate-message.outputs.daily-message }}'"
